routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', 'LoginController@index')->name('login');
Route::post('/login', 'LoginController@store');

Route::middleware('auth')
	->group(function() {
        //logincontroller
        //logout
		Route::get('/logout', 'LoginController@logout');
		//change password
        Route::get('/changepassword','LoginController@showChangePasswordForm');
        Route::post('/changepassword','LoginController@changePassword')->name('changepassword');

		//eventcontroller
        Route::get('/', function () {
		    return view('/events/index');
		});
		Route::resource('/events','EventController');
		//show all events
		Route::get('/showAll','EventController@showAll');
		//edit event
		Route::post('/events/{event}/updateAll', 'EventController@updateAll');
		//delete one event
		Route::get('/events/{event}/delete', 'EventController@delete');
		//search
		Route::get('/search','EventController@search');






});

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    //
    protected $guarded = [];
     protected $fillable = ['title', 'description', 'facility_category_id','start_date','end_date'];

    public function getRouteKeyName(){
        return 'title';
    }

    public function facility_category()
    {
    	return $this->belongsTo(FacilityCategory::class);
    }
    
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Event;
use App\FacilityCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return $this->eventsToArray(Event::all());
    }

    public function eventsToArray($events){
        $eventsArray = [];
        foreach($events as $event){
            $data = [
                "title" => $event->title,
                "start" => $event->start_date,
                "end" => $event->end_date,
                "textColor" => "white"
            ];
            array_push($eventsArray,$data);
        }
        return response()->json($eventsArray);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $facility_categories = FacilityCategory::all();
        return view('events/create', compact('facility_categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validate the form
        request()->validate([
            'title' => 'required',
            'description' => 'required',
            'facility_category_id' => 'required',
            'start_date' => 'required',
            'end_date' => 'required'        
        ]);
        //store the model
        Event::create([
            "title" => $request->title,
            "description" => $request->description,
            "facility_category_id" => $request->facility_category_id,
            "start_date" => $request->start_date,
            "end_date" => $request->end_date
        ]);
        return redirect('/');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function show(Event $event)
    {
        //
        return view('events/show')->withEvent($event);
    }

     public function showAll()
    {
        //
        $events = Event::all();
        $facility_categories = FacilityCategory::all();
        return view('events/showAll', compact('events', 'facility_categories'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function edit(Event $event)
    {
        //
        
        $facility_categories = FacilityCategory::all();
        return view('events/edit', compact('event', 'facility_categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Event $event)
    {
        //
        $event->update([
            "start_date" => $request->start,
            "end_date" => $request->end
        ]);
        return response()->json(['success'=>'updated']);
    }

    public function updateAll(Event $event)
    {
        request()->validate([
            'title' => 'required',
            "description" => 'required',
            'start_date' => 'required',
            'end_date' => 'required',
            'facility_category_id' => 'required'
        ]);
        $event->update(request()->only([
            'title', 'description', 'start_date', 'end_date', 'facility_category_id'
        ]));

        return redirect('/showAll');
    }

        

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
     public function destroy(Event $event)
    {
         $event->delete();
        return response()->json(['success'=>'deleted']);
    }

    public function delete(Event $event)
    {

        $event->delete();
        return redirect('/showAll');
    }

     public function search(Request $request)
    {
         $events = Event::get();
        $search = \Request::get('search'); 
        $events = Event::where('title','like','%'.$search.'%')
            ->orWhereHas('facility_category', function ($query) use ($search) {
                $query->where('name', 'like', '%'.$search.'%');
            })
            ->orderBy('id')
            ->paginate(4);

        return view('events.showAll', compact('events'));
        
    }


}

?>

resources/views/events/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="row">
        <div class="col-md-8 mx-auto my-4">
            <div class="card">
                <div class="card-header bg-dark text-white">
                    <h5 class="card-title p-0 m-0">Add an Event</h5>
                </div>
                <div class="card-body">
                    <form action="{{route('events.store')}}" method="post">
                        @csrf
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <div class="container">
                            <fieldset class="form-group row">
                                <legend class="col-form-legend col-sm-1-12">Title</legend>
                                <div class="col-sm-1-12">
                                    <input type="text" class="form-control" name="title" id="title" placeholder="Title">
                                </div>
                            </fieldset>

                            <fieldset class="form-group row">
                                <legend class="col-form-legend col-sm-1-12">Description</legend>
                                <div class="col-sm-1-12">
                                    <textarea class="form-control" name="description" id="description" placeholder="Description"></textarea>
                                </div>
                            </fieldset>

                                <div class="form-group row">
                                    <legend class="col-form-legend col-sm-1-12">Facility Category</legend>
                                    <select name="facility_category_id" id="" class="form-control">
                                        @foreach($facility_categories as $category)
                                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                </div>

                            <fieldset class="form-group row">
                                <legend class="col-form-legend col-sm-1-12">Date Started</legend>
                                <div class="col-sm-1-12">
                                    <input type="date" class="form-control" name="start_date" id="start_date" placeholder="Date Started">
                                </div>
                            </fieldset>

                            <fieldset class="form-group row">
                                <legend class="col-form-legend col-sm-1-12">Date End</legend>
                                <div class="col-sm-1-12">
                                    <input type="date" class="form-control" name="end_date" id="end_date" placeholder="Date End">
                                </div>
                            </fieldset>

                            <div class="form-group row">
                                <div class="col-sm-12">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </div>
                            
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/events/edit.blade.php
@extends('layouts.master')

@section('content')
<link rel="stylesheet" href="">
<style>
    textarea {
        resize: none;
    }
</style>
    <div class="row">
        <div class="col-md-8 mx-auto my-4">
            <div class="card">
                <div class="card-body">
				<form action="/events/{{ $event->title }}/updateAll" method="post">
                    @csrf
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
		
                    <div class="col-sm-8 font-weight-bold float-right">
                      <label for="Description">Description:</label>
                      <textarea class="form-control " name="description" id="description"  rows="14" resize:none>{{ $event->description }}</textarea>
                    </div>

                    <div class="col-sm-4 font-weight-bold">
                        <div class="form-group">
                            <label for="Title">Title:</label>
                            <input type="text" name="title" placeholder="Title" class='form-control'
                                value="{{ $event->title }}">
                        </div>
                    </div>

                    <div class="col-sm-4 font-weight-bold">
                        <div class="form-group">
                            <label for="Date Started">Date Started:</label>
                            <input type="date" name="start_date" placeholder="Date Started" class='form-control'
                                value="{{ $event->start_date }}">
                        </div>
                    </div>

                    <div class="col-sm-4 font-weight-bold">
                        <div class="form-group">
                            <label for="Date End">Date End:</label>
                            <input type="date" name="end_date" placeholder="Date End" class='form-control'
                                value="{{ $event->end_date }}">
                        </div>
                    </div>

                    <div class="col-sm-4 font-weight-bold">
                        <div class="form-group">
                            <label for="Facility Category">Facility Category</label>
                            <select name="facility_category_id" id="" class="form-control" required>
                                @foreach($facility_categories as $category)
                                    {{-- check if category id matches --}}
                                    @if($category->id == $event->facility_category_id)
                                        {{-- yes then select the option --}}
                                        <option value="{{ $category->id }}" selected>{{ $category->name }}</option>
                                    @else
                                        {{-- no then just display it --}}
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endif
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                    </div>

				</form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/events/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="row">
        <div class="col-md-10 mx-auto my-4">
            <div id='calendar'></div>  
        </div>
    </div>
@endsection

@section('scripts')

    <script>
        


        document.addEventListener('DOMContentLoaded', function() {
            var calendarEl = document.getElementById('calendar');//your dive id of calendar
            var calendar = new FullCalendar.Calendar(calendarEl, {
                plugins: [ 'interaction', 'dayGrid' ],
                header: {
                    left: 'prevYear,prev,next,nextYear today',
                    center: 'title',
                    right: 'dayGridMonth,dayGridWeek,dayGridDay'
                },
                defaultDate: '{{ date('Y-m-d') }}',
                navLinks: true, // can click day/week names to navigate views
                editable: true,
                selectable: true,
                selectHelper:true,
                select : function(selectionInfo){ //trigger select event
                    let formatted_start_date = selectionInfo.start.getFullYear() + "-" + (selectionInfo.start.getMonth() + 1) + "-" + selectionInfo.start.getDate() + " " + selectionInfo.start.getHours() + ":" + selectionInfo.start.getMinutes() + ":" + selectionInfo.start.getSeconds(); 
                    let formatted_end_date = selectionInfo.end.getFullYear() + "-" + (selectionInfo.end.getMonth() + 1) + "-" + selectionInfo.end.getDate() + " " + selectionInfo.end.getHours() + ":" + selectionInfo.end.getMinutes() + ":" + selectionInfo.end.getSeconds();
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                },
                 
                eventLimit: true, // allow "more" link when too many events
                events :  '/events',
                eventClick: function(info) {// trigger click event
                    const swalWithBootstrapButtons = Swal.mixin({
                        customClass: {
                            confirmButton: 'btn btn-info mx-2',
                            cancelButton: 'btn btn-danger'
                        },
                        buttonsStyling: false
                    })

                    swalWithBootstrapButtons.fire({
                            title: 'Choose Action',
                            icon: 'info',
                            showCancelButton: true,
                            cancelButtonText: 'Remove',
                            confirmButtonText: 'View',
                            reverseButtons: false
                        }).then((result) => {
                        if (result.value) {
                            let link = `http://127.0.0.1:8000/events/${info.event.title}`;
                            window.location.href = link;
                        }else{
                            $.ajaxSetup({
                                headers: {
                                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                                }
                            });
                            $.ajax({
                                type:'DELETE',
                                url : "/events/" + info.event.title,
                                success:function(){
                                    Swal.fire({
                                        position: 'center',
                                        icon: 'success',
                                        title: 'Event Deleted',
                                        showConfirmButton: false,
                                        timer: 1500
                                    })
                                    location.reload();
                                }
                            });
                        }
                    })

                },
                eventDrop: function(info) { //trigger drop event
                    let formatted_start_date = info.event.start.getFullYear() + "-" + (info.event.start.getMonth() + 1) + "-" + info.event.start.getDate() + " " + info.event.start.getHours() + ":" + info.event.start.getMinutes() + ":" + info.event.start.getSeconds(); 
                    let formatted_end_date = info.event.end.getFullYear() + "-" + (info.event.end.getMonth() + 1) + "-" + info.event.end.getDate() + " " + info.event.end.getHours() + ":" + info.event.end.getMinutes() + ":" + info.event.end.getSeconds();
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        type:'PUT',
                        url : "/events/" + info.event.title,
                        data:{
                            title:info.event.title, 
                            start:formatted_start_date, 
                            end:formatted_end_date
                        },
                        success:function(){
                            Swal.fire({
                                position: 'center',
                                icon: 'success',
                                title: 'Event Changed',
                                showConfirmButton: false,
                                timer: 1500
                            })
                        }
                    });
                },
                eventResize : function(eventResizeInfo){//trigger event resize
                    let formatted_start_date = eventResizeInfo.event.start.getFullYear() + "-" + (eventResizeInfo.event.start.getMonth() + 1) + "-" + eventResizeInfo.event.start.getDate() + " " + eventResizeInfo.event.start.getHours() + ":" + eventResizeInfo.event.start.getMinutes() + ":" + eventResizeInfo.event.start.getSeconds(); 
                    let formatted_end_date = eventResizeInfo.event.end.getFullYear() + "-" + (eventResizeInfo.event.end.getMonth() + 1) + "-" + eventResizeInfo.event.end.getDate() + " " + eventResizeInfo.event.end.getHours() + ":" + eventResizeInfo.event.end.getMinutes() + ":" + eventResizeInfo.event.end.getSeconds();
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        type:'PUT',
                        url : "/events/" + eventResizeInfo.event.title,
                        data:{
                            title:eventResizeInfo.event.title, 
                            start:formatted_start_date, 
                            end:formatted_end_date
                        },
                        success:function(){
                            Swal.fire({
                                position: 'center',
                                icon: 'success',
                                title: 'Event Changed',
                                showConfirmButton: false,
                                timer: 1500
                            })
                        }
                    });
                }
            });
            calendar.setOption('locale', 'en');           
            calendar.render();
            document.querySelector('.fc-dayGridMonth-button').innerHTML = "Month";
            document.querySelector('.fc-dayGridWeek-button').innerHTML = "Week";
            document.querySelector('.fc-dayGridDay-button').innerHTML = "Day";
            document.querySelector('.fc-today-button').innerHTML = "Today";
        });

    </script>
    
    <div class="container">
        <div class="row">
            <div class="col-sm-12 d-flex justify-content-center">
                <a href="events/create" class="btn btn-primary">Create an Event</a>
            </div>
        </div>
    </div>

@endsection

resources/views/events/show.blade.php
@extends('layouts.master')

@section('content')
<link rel="stylesheet" href="">
<style>
    textarea {
        resize: none;
    }
</style>

    <div class="row">
        <div class="col-md-8 mx-auto my-4">
            <div class="card">
                <div class="card-body">

                    <div class="col-sm-8 font-weight-bold float-right">
                      <label for="Description">Description:</label>
                      <textarea class="form-control " name="description" id="description"  rows="14" resize:none disabled>{{ $event->description }}</textarea>
                    </div>


                    <div class="col-sm-4 font-weight-bold">
                        <div class="form-group">
                            <label for="Title">Title:</label>
                            <input type="text" name="title" placeholder="Title" class='form-control text-danger'
                                value="{{ $event->title }}" disabled>
                        </div>
                    </div>

                    <div class="col-sm-4 font-weight-bold">
                        <div class="form-group">
                            <label for="Date Started">Date Started:</label>
                            <input type="date" name="start_date" placeholder="Date Started" class='form-control text-danger'
                                value="{{ $event->start_date }}" disabled>
                        </div>
                    </div>

                    <div class="col-sm-4 font-weight-bold">
                        <div class="form-group">
                            <label for="Date End">Date End:</label>
                            <input type="date" name="end_date" placeholder="Date End" class='form-control text-danger'
                                value="{{ $event->end_date }}" disabled>
                        </div>
                    </div>

                    <div class="col-sm-4 font-weight-bold">
                        <div class="form-group">
                            <label for="Facility Category">Facility:</label>
                            <input type="text" name="facility_category_id" placeholder="Facility Category" class='form-control text-danger'
                                value="{{ $event->facility_category->name }}" disabled>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <a href="javascript:history.back()" class="btn btn-primary">Go Back</a>
                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/events/showAll.blade.php
@extends('layouts.master')
@section('content')
	<div class="card">
		<div class="card-header">
			<h5>Equipment</h5>
		</div>
		<div class="card-body">
			<a href = '/events/create' class="btn btn-primary">Add an Event</a>
			<hr>

			<div class="col-sm-12 d-flex justify-content-end">
				<form action="/search" method="get">
					<div class="form-group d-flex justify-content-end">
						<input type="text" name="search" class="form-control" placeholder="Search">
						<span class="form-group-btn col-sm-3 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Search</button>
						</span>
						<span class="form-group-btn sm-2 d-flex justify-content-end">
							<a href="showAll" class="btn btn-dark">Reset</a>
						</span>
					</div>
				</form>
			</div>


			<table class="table table-bordered">
				<thead>
					<tr>
						<th>Title</th>
						<th>Start Date</th>
						<th>End Date</th>
						<th>Facility</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					@foreach($events as $event)
						<tr>
							<td>{{ $event->title }}</td>
							<td>{{ $event->start_date }}</td>
							<td>{{ $event->end_date }}</td>
							<td>{{ $event->facility_category->name }}</td>
							<td>
								<a href="/events/{{ $event->title }}" class="btn btn-primary">View</a>
								<a href="/events/{{ $event->title }}/edit" class="btn btn-info">Edit</a>
								<a href="/events/{{ $event->title }}/delete" class="btn btn-danger">Delete</a>
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>

			
		</div>
	</div>
@endsection